### ISSUE TITLE
focusing

### ISSUE THREAD

**Issue by GulfwebKw** [Taha-Firoz/virtual.keyboard.dart#1]
cant focus on textfield when typing with virtual keyboard

**Comment by Taha-Firoz** [comment]
Yes that's an issue with how it's implemented. Flutter doesn't yet provide an api to emulate a native or window manager provided keyboard so we're unable to focus on the text field when typing. There was a previous version which did have the feature but it was too distracting because whenever you touch the keyboard the text field loses focus.
